/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AanpakRouteImport } from './routes/aanpak'
import { Route as AdviesgesprekRouteImport } from './routes/adviesgesprek'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DetacheringRouteImport } from './routes/detachering'
import { Route as DienstenRouteImport } from './routes/diensten'
import { Route as ExtraDienstenRouteImport } from './routes/extra-diensten'
import { Route as KenniscentrumRouteImport } from './routes/kenniscentrum'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OverRouteImport } from './routes/over'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as UitzendenRouteImport } from './routes/uitzenden'
import { Route as VacaturesRouteImport } from './routes/vacatures'
import { Route as VoorOpdrachtgeversRouteImport } from './routes/voor-opdrachtgevers'
import { Route as VoorProfessionalsRouteImport } from './routes/voor-professionals'
import { Route as WervingSelectieRouteImport } from './routes/werving-selectie'
import { Route as ZzpRouteImport } from './routes/zzp'
import { Route as KenniscentrumIndexRouteImport } from './routes/kenniscentrum.index'
import { Route as KenniscentrumSlugRouteImport } from './routes/kenniscentrum.$slug'
import { Route as VacaturesIndexRouteImport } from './routes/vacatures.index'
import { Route as VacaturesSlugRouteImport } from './routes/vacatures.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AanpakRoute = AanpakRouteImport.update({
  id: '/aanpak',
  path: '/aanpak',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviesgesprekRoute = AdviesgesprekRouteImport.update({
  id: '/adviesgesprek',
  path: '/adviesgesprek',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DetacheringRoute = DetacheringRouteImport.update({
  id: '/detachering',
  path: '/detachering',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenRoute = DienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtraDienstenRoute = ExtraDienstenRouteImport.update({
  id: '/extra-diensten',
  path: '/extra-diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const KenniscentrumRoute = KenniscentrumRouteImport.update({
  id: '/kenniscentrum',
  path: '/kenniscentrum',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverRoute = OverRouteImport.update({
  id: '/over',
  path: '/over',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const UitzendenRoute = UitzendenRouteImport.update({
  id: '/uitzenden',
  path: '/uitzenden',
  getParentRoute: () => rootRouteImport,
} as any)
const VacaturesRoute = VacaturesRouteImport.update({
  id: '/vacatures',
  path: '/vacatures',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorOpdrachtgeversRoute = VoorOpdrachtgeversRouteImport.update({
  id: '/voor-opdrachtgevers',
  path: '/voor-opdrachtgevers',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorProfessionalsRoute = VoorProfessionalsRouteImport.update({
  id: '/voor-professionals',
  path: '/voor-professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const WervingSelectieRoute = WervingSelectieRouteImport.update({
  id: '/werving-selectie',
  path: '/werving-selectie',
  getParentRoute: () => rootRouteImport,
} as any)
const ZzpRoute = ZzpRouteImport.update({
  id: '/zzp',
  path: '/zzp',
  getParentRoute: () => rootRouteImport,
} as any)
const KenniscentrumIndexRoute = KenniscentrumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KenniscentrumRoute,
} as any)
const KenniscentrumSlugRoute = KenniscentrumSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KenniscentrumRoute,
} as any)
const VacaturesIndexRoute = VacaturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VacaturesRoute,
} as any)
const VacaturesSlugRoute = VacaturesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VacaturesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aanpak': typeof AanpakRoute
  '/adviesgesprek': typeof AdviesgesprekRoute
  '/contact': typeof ContactRoute
  '/detachering': typeof DetacheringRoute
  '/diensten': typeof DienstenRoute
  '/extra-diensten': typeof ExtraDienstenRoute
  '/kenniscentrum': typeof KenniscentrumRouteWithChildren
  '/login': typeof LoginRoute
  '/over': typeof OverRoute
  '/portal': typeof PortalRoute
  '/uitzenden': typeof UitzendenRoute
  '/vacatures': typeof VacaturesRouteWithChildren
  '/voor-opdrachtgevers': typeof VoorOpdrachtgeversRoute
  '/voor-professionals': typeof VoorProfessionalsRoute
  '/werving-selectie': typeof WervingSelectieRoute
  '/zzp': typeof ZzpRoute
  '/kenniscentrum/$slug': typeof KenniscentrumSlugRoute
  '/vacatures/$slug': typeof VacaturesSlugRoute
  '/kenniscentrum/': typeof KenniscentrumIndexRoute
  '/vacatures/': typeof VacaturesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aanpak': typeof AanpakRoute
  '/adviesgesprek': typeof AdviesgesprekRoute
  '/contact': typeof ContactRoute
  '/detachering': typeof DetacheringRoute
  '/diensten': typeof DienstenRoute
  '/extra-diensten': typeof ExtraDienstenRoute
  '/login': typeof LoginRoute
  '/over': typeof OverRoute
  '/portal': typeof PortalRoute
  '/uitzenden': typeof UitzendenRoute
  '/voor-opdrachtgevers': typeof VoorOpdrachtgeversRoute
  '/voor-professionals': typeof VoorProfessionalsRoute
  '/werving-selectie': typeof WervingSelectieRoute
  '/zzp': typeof ZzpRoute
  '/kenniscentrum/$slug': typeof KenniscentrumSlugRoute
  '/vacatures/$slug': typeof VacaturesSlugRoute
  '/kenniscentrum': typeof KenniscentrumIndexRoute
  '/vacatures': typeof VacaturesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aanpak': typeof AanpakRoute
  '/adviesgesprek': typeof AdviesgesprekRoute
  '/contact': typeof ContactRoute
  '/detachering': typeof DetacheringRoute
  '/diensten': typeof DienstenRoute
  '/extra-diensten': typeof ExtraDienstenRoute
  '/kenniscentrum': typeof KenniscentrumRouteWithChildren
  '/login': typeof LoginRoute
  '/over': typeof OverRoute
  '/portal': typeof PortalRoute
  '/uitzenden': typeof UitzendenRoute
  '/vacatures': typeof VacaturesRouteWithChildren
  '/voor-opdrachtgevers': typeof VoorOpdrachtgeversRoute
  '/voor-professionals': typeof VoorProfessionalsRoute
  '/werving-selectie': typeof WervingSelectieRoute
  '/zzp': typeof ZzpRoute
  '/kenniscentrum/$slug': typeof KenniscentrumSlugRoute
  '/vacatures/$slug': typeof VacaturesSlugRoute
  '/kenniscentrum/': typeof KenniscentrumIndexRoute
  '/vacatures/': typeof VacaturesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aanpak'
    | '/adviesgesprek'
    | '/contact'
    | '/detachering'
    | '/diensten'
    | '/extra-diensten'
    | '/kenniscentrum'
    | '/login'
    | '/over'
    | '/portal'
    | '/uitzenden'
    | '/vacatures'
    | '/voor-opdrachtgevers'
    | '/voor-professionals'
    | '/werving-selectie'
    | '/zzp'
    | '/kenniscentrum/$slug'
    | '/vacatures/$slug'
    | '/kenniscentrum/'
    | '/vacatures/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aanpak'
    | '/adviesgesprek'
    | '/contact'
    | '/detachering'
    | '/diensten'
    | '/extra-diensten'
    | '/login'
    | '/over'
    | '/portal'
    | '/uitzenden'
    | '/voor-opdrachtgevers'
    | '/voor-professionals'
    | '/werving-selectie'
    | '/zzp'
    | '/kenniscentrum/$slug'
    | '/vacatures/$slug'
    | '/kenniscentrum'
    | '/vacatures'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/aanpak'
    | '/adviesgesprek'
    | '/contact'
    | '/detachering'
    | '/diensten'
    | '/extra-diensten'
    | '/kenniscentrum'
    | '/login'
    | '/over'
    | '/portal'
    | '/uitzenden'
    | '/vacatures'
    | '/voor-opdrachtgevers'
    | '/voor-professionals'
    | '/werving-selectie'
    | '/zzp'
    | '/kenniscentrum/$slug'
    | '/vacatures/$slug'
    | '/kenniscentrum/'
    | '/vacatures/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AanpakRoute: typeof AanpakRoute
  AdviesgesprekRoute: typeof AdviesgesprekRoute
  ContactRoute: typeof ContactRoute
  DetacheringRoute: typeof DetacheringRoute
  DienstenRoute: typeof DienstenRoute
  ExtraDienstenRoute: typeof ExtraDienstenRoute
  KenniscentrumRoute: typeof KenniscentrumRouteWithChildren
  LoginRoute: typeof LoginRoute
  OverRoute: typeof OverRoute
  PortalRoute: typeof PortalRoute
  UitzendenRoute: typeof UitzendenRoute
  VacaturesRoute: typeof VacaturesRouteWithChildren
  VoorOpdrachtgeversRoute: typeof VoorOpdrachtgeversRoute
  VoorProfessionalsRoute: typeof VoorProfessionalsRoute
  WervingSelectieRoute: typeof WervingSelectieRoute
  ZzpRoute: typeof ZzpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanpak': {
      id: '/aanpak'
      path: '/aanpak'
      fullPath: '/aanpak'
      preLoaderRoute: typeof AanpakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adviesgesprek': {
      id: '/adviesgesprek'
      path: '/adviesgesprek'
      fullPath: '/adviesgesprek'
      preLoaderRoute: typeof AdviesgesprekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detachering': {
      id: '/detachering'
      path: '/detachering'
      fullPath: '/detachering'
      preLoaderRoute: typeof DetacheringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten': {
      id: '/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof DienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extra-diensten': {
      id: '/extra-diensten'
      path: '/extra-diensten'
      fullPath: '/extra-diensten'
      preLoaderRoute: typeof ExtraDienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kenniscentrum': {
      id: '/kenniscentrum'
      path: '/kenniscentrum'
      fullPath: '/kenniscentrum'
      preLoaderRoute: typeof KenniscentrumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over': {
      id: '/over'
      path: '/over'
      fullPath: '/over'
      preLoaderRoute: typeof OverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uitzenden': {
      id: '/uitzenden'
      path: '/uitzenden'
      fullPath: '/uitzenden'
      preLoaderRoute: typeof UitzendenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacatures': {
      id: '/vacatures'
      path: '/vacatures'
      fullPath: '/vacatures'
      preLoaderRoute: typeof VacaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voor-opdrachtgevers': {
      id: '/voor-opdrachtgevers'
      path: '/voor-opdrachtgevers'
      fullPath: '/voor-opdrachtgevers'
      preLoaderRoute: typeof VoorOpdrachtgeversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voor-professionals': {
      id: '/voor-professionals'
      path: '/voor-professionals'
      fullPath: '/voor-professionals'
      preLoaderRoute: typeof VoorProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werving-selectie': {
      id: '/werving-selectie'
      path: '/werving-selectie'
      fullPath: '/werving-selectie'
      preLoaderRoute: typeof WervingSelectieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zzp': {
      id: '/zzp'
      path: '/zzp'
      fullPath: '/zzp'
      preLoaderRoute: typeof ZzpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kenniscentrum/': {
      id: '/kenniscentrum/'
      path: '/'
      fullPath: '/kenniscentrum/'
      preLoaderRoute: typeof KenniscentrumIndexRouteImport
      parentRoute: typeof KenniscentrumRoute
    }
    '/kenniscentrum/$slug': {
      id: '/kenniscentrum/$slug'
      path: '/$slug'
      fullPath: '/kenniscentrum/$slug'
      preLoaderRoute: typeof KenniscentrumSlugRouteImport
      parentRoute: typeof KenniscentrumRoute
    }
    '/vacatures/': {
      id: '/vacatures/'
      path: '/'
      fullPath: '/vacatures/'
      preLoaderRoute: typeof VacaturesIndexRouteImport
      parentRoute: typeof VacaturesRoute
    }
    '/vacatures/$slug': {
      id: '/vacatures/$slug'
      path: '/$slug'
      fullPath: '/vacatures/$slug'
      preLoaderRoute: typeof VacaturesSlugRouteImport
      parentRoute: typeof VacaturesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KenniscentrumRouteChildren {
  KenniscentrumSlugRoute: typeof KenniscentrumSlugRoute
  KenniscentrumIndexRoute: typeof KenniscentrumIndexRoute
}

const KenniscentrumRouteChildren: KenniscentrumRouteChildren = {
  KenniscentrumSlugRoute: KenniscentrumSlugRoute,
  KenniscentrumIndexRoute: KenniscentrumIndexRoute,
}

const KenniscentrumRouteWithChildren = KenniscentrumRoute._addFileChildren(
  KenniscentrumRouteChildren,
)

interface VacaturesRouteChildren {
  VacaturesSlugRoute: typeof VacaturesSlugRoute
  VacaturesIndexRoute: typeof VacaturesIndexRoute
}

const VacaturesRouteChildren: VacaturesRouteChildren = {
  VacaturesSlugRoute: VacaturesSlugRoute,
  VacaturesIndexRoute: VacaturesIndexRoute,
}

const VacaturesRouteWithChildren = VacaturesRoute._addFileChildren(
  VacaturesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AanpakRoute: AanpakRoute,
  AdviesgesprekRoute: AdviesgesprekRoute,
  ContactRoute: ContactRoute,
  DetacheringRoute: DetacheringRoute,
  DienstenRoute: DienstenRoute,
  ExtraDienstenRoute: ExtraDienstenRoute,
  KenniscentrumRoute: KenniscentrumRouteWithChildren,
  LoginRoute: LoginRoute,
  OverRoute: OverRoute,
  PortalRoute: PortalRoute,
  UitzendenRoute: UitzendenRoute,
  VacaturesRoute: VacaturesRouteWithChildren,
  VoorOpdrachtgeversRoute: VoorOpdrachtgeversRoute,
  VoorProfessionalsRoute: VoorProfessionalsRoute,
  WervingSelectieRoute: WervingSelectieRoute,
  ZzpRoute: ZzpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
